#!/bin/sh /etc/rc.common
# {# jinja-parse #}
INSTALL_PREFIX={{INSTALL_PREFIX}}

USE_PROCD=1
START=15
STOP=15

OPENSYNC_DB=${INSTALL_PREFIX}/etc/conf.db.bck
OPENSYNC_SCHEMA=${INSTALL_PREFIX}/etc/opensync.ovsschema
OVS_DB_DIR=/var/run/openvswitch
OVS_DB=/var/run/openvswitch/conf.db

start_ovs() {
        uci set openvswitch.ovs.disabled=0
        uci set openvswitch.north.disabled=0
        uci set openvswitch.controller.disabled=0
        uci commit openvswitch

        echo "Starting OVS"
        if [ ! -d ${OVS_DB_DIR} ]; then
            mkdir -p ${OVS_DB_DIR}
        fi
        cp ${OPENSYNC_DB} ${OVS_DB}
        procd_open_instance
        procd_set_param command /bin/sh
        procd_append_param command /usr/share/openvswitch/scripts/ovs-ctl
        procd_append_param command start --db-file=${OVS_DB} --db-schema=${OPENSYNC_SCHEMA} --system-id=1
        procd_close_instance
}

stop_ovs() {
        echo "Stopping OVS"
        /usr/share/openvswitch/scripts/ovs-ctl stop
}

start_service() {
    stop_ovs
    start_ovs
}

stop_service() {
    stop_ovs
}
