#!/bin/sh /etc/rc.common
# {# jinja-parse #}
INSTALL_PREFIX={{INSTALL_PREFIX}}

USE_PROCD=1
START=90
STOP=90

PROG="${INSTALL_PREFIX}/bin/dm"
OPENSYNC_DB=${INSTALL_PREFIX}/etc/conf.db.bck
OPENSYNC_SCHEMA=${INSTALL_PREFIX}/etc/opensync.ovsschema
OVS_DB_DIR=/var/run/openvswitch
OVS_DB=/var/run/openvswitch/conf.db
CERTS_DEST_PATH=/var/run/openvswitch/certs
CERTS_SRC_PATH=${INSTALL_PREFIX}/certs

start_service() {
    ${INSTALL_PREFIX}/bin/reg_dom_update.sh
    procd_open_instance
    echo "Setting certificates"
    mkdir -p ${CERTS_DEST_PATH}
    cp ${CERTS_SRC_PATH}/* ${CERTS_DEST_PATH}/
    ${INSTALL_PREFIX}/bin/start.sh
    echo "Starting OpenSync"
    procd_set_param command ${PROG}
    procd_close_instance
}

stop_service() {
    echo "Removing certificates"
    rm -rf ${CERTS_DEST_PATH}
    echo "Killing managers"
    killall -9 dm wm sm cm nm lm qm cmdm rrm um uccm udhcpc dnsmasq
}
